const actionTypes = {
    GET_SEARCH_RESULTS_REQUEST: 'GET_SEARCH_RESULTS_REQUEST',
    GET_SEARCH_RESULTS_SUCCESS: 'GET_SEARCH_RESULTS_SUCCESS',
    GET_SEARCH_RESULTS_FAILURE: ' GET_SEARCH_RESULTS_FAILURE',
    ADD_SEARCH_ITEM:'ADD_SEARCH_ITEM',
    DELETE_SEARCH_ITEM:'DELETE_SEARCH_ITEM',
    EDIT_SEARCH_ITEM:'EDIT_SEARCH_ITEM'
  };

  
  export default actionTypes;